[package]
name = "muse"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
minijinja = { version = "2.8.0", features = ["loader"] }
minijinja-autoreload = "2.8.0"
tokio = { version = "1.44.0", features = ["full"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.3", features = [
    "runtime-tokio-native-tls",
    "sqlite",
    "mysql",
    "uuid",
    "chrono"
] }
chrono = "0.4.40"
uuid = { version = "1.15.1", features = ["v4"] }



rust-embed = "8.6.0"
serde_json = "1.0.140"
reqwest = { version = "0.12.12", features = ["json"] }
tower-http = { version = "0.6.2", features = ["fs"] }