[package]
name = "muse"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
minijinja = { version = "2.8.0", features = ["loader"] }
minijinja-autoreload = "2.8.0"
tokio = { version = "1.44.0", features = ["full"] }
dotenvy = "0.15.7"
serde = { version = "1.0.219", features = ["derive"] }
sqlx = { version = "0.8.3", features = [
    "runtime-tokio-native-tls",
    "sqlite"
] }
chrono = "0.4.40"
uuid = { version = "1.15.1", features = ["v4"] }
rust-embed = "8.6.0"
async-stream = "0.3.6"
bytes = "1.10.1"
reqwest = { version = "0.11", features = ["json"] }
base64 = "0.21"
serde_json = "1.0.140"